In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
iris = datasets.load_iris()
iris_data = iris.data # 花萼 長度 花萼 寬度 花瓣長度 屬種
iris_label = iris.target

In [3]:
iris_data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
#由於KNN分類法是藉由確認最近的觀察值來預測分類，因此變數的比例就會影響很大。
#載入標準化比例尺（StandardScaler）套件
from sklearn.preprocessing import StandardScaler
iris_data = pd.DataFrame(iris_data)

scaler = StandardScaler()
scaler.fit(iris_data)
scaled_features = scaler.transform(iris_data)
df_feat = pd.DataFrame(scaled_features,columns=iris_data.columns)
df_feat.head()

0         1         2         3
0 -0.900681  1.019004 -1.340227 -1.315444
1 -1.143017 -0.131979 -1.340227 -1.315444
2 -1.385353  0.328414 -1.397064 -1.315444
3 -1.506521  0.098217 -1.283389 -1.315444
4 -1.021849  1.249201 -1.340227 -1.315444

In [5]:
train_data , test_data , train_label , test_label = train_test_split(df_feat,iris_label,test_size=0.2) # 切資料

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_data, train_label)
y_pred = gnb.predict(test_data)

# print("Number of mislabeled points out of a total %d points : %d"
#  % (iris.data.shape[0],(iris.target != y_pred).sum()))
# Number of mislabeled points out of a total 150 points : 6

In [7]:
print(y_pred)

[2 1 2 0 1 0 0 2 1 2 2 1 1 2 1 2 1 2 1 1 2 2 2 0 0 2 2 2 1 0]


In [8]:
print(test_label)

[2 1 2 0 1 0 0 2 1 2 1 1 1 2 1 2 1 2 1 1 2 2 2 0 0 2 2 2 1 0]


In [10]:
from sklearn.metrics import precision_recall_curve 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
#看表現 01
pred = gnb.predict(test_data)

print('WITH K=40')
print('\n')
print(confusion_matrix(test_label,pred))
print('\n')
print(classification_report(test_label,pred))

WITH K=40


[[ 6  0  0]
 [ 0 10  1]
 [ 0  0 13]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.91      0.95        11
           2       0.93      1.00      0.96        13

    accuracy                           0.97        30
   macro avg       0.98      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

