In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
iris = datasets.load_iris()
x = pd.DataFrame(iris['data'], columns=iris['feature_names'])
print("target_names: "+str(iris['target_names']))
y = pd.DataFrame(iris['target'], columns=['target'])
iris_data = pd.concat([x,y], axis=1)
iris_data = iris_data[['sepal length (cm)','petal length (cm)','target']]
iris_data = iris_data[iris_data['target'].isin([0,1])]
iris_data.head(3)

target_names: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  petal length (cm)  target
0                5.1                1.4       0
1                4.9                1.4       0
2                4.7                1.3       0

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
iris_data[['sepal length (cm)','petal length (cm)']], iris_data[['target']], test_size=0.2, random_state=0)

In [4]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [5]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(X_train, y_train)  

C:\Users\LAB\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [6]:
clf.score(X_train, y_train) 

1.0

In [7]:
clf.decision_path(X_train)  

(<80x722 sparse matrix of type '<class 'numpy.int64'>'
 	with 21745 stored elements in Compressed Sparse Row format>,
 array([  0,   9,  12,  15,  22,  25,  28,  31,  44,  47,  58,  73,  80,
         83,  94, 105, 108, 111, 114, 117, 144, 153, 172, 175, 184, 187,
        190, 193, 206, 219, 226, 237, 244, 255, 258, 271, 280, 283, 290,
        293, 310, 313, 334, 337, 340, 359, 376, 383, 386, 389, 392, 395,
        406, 409, 416, 421, 424, 433, 446, 449, 452, 455, 458, 467, 470,
        479, 482, 495, 502, 519, 522, 541, 544, 547, 550, 557, 560, 563,
        570, 573, 576, 599, 602, 609, 620, 623, 630, 633, 648, 661, 664,
        671, 674, 683, 686, 689, 692, 705, 716, 719, 722], dtype=int32))

In [8]:
clf.apply(X_train)

array([[ 2,  1,  1, ...,  2,  1,  1],
       [ 8,  2,  2, ..., 10,  2,  2],
       [ 2,  1,  1, ...,  2,  1,  1],
       ...,
       [ 7,  2,  2, ...,  8,  2,  2],
       [ 2,  1,  1, ...,  2,  1,  1],
       [ 2,  1,  1, ...,  2,  1,  1]], dtype=int64)

In [9]:
from sklearn.metrics import precision_recall_curve 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
#看表現 01
pred = clf.predict(X_test)

print('WITH K=40')
print('\n')
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

WITH K=40


[[10  0]
 [ 0 10]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

   micro avg       1.00      1.00      1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

