In [84]:
import numpy as np
import sys
import math

DNA_SIZE = 3           # DNA length      DNA 長度 維度
DNA_MAX  = 5             # DNA 編碼
POP_SIZE = 10          # population size 人口長度  
CROSS_RATE = 1         # crossover probability 
MUTATION_RATE = 0.2    # mutation probability 
MFE = POP_SIZE  * 1         #計算fintneess 次數
MFE_COUNT = 0
X_BOUND = [-3, DNA_MAX]         # x upper and lower bounds 上下限
pop = np.random.uniform(X_BOUND[0],DNA_MAX , size=(POP_SIZE, DNA_SIZE + 1))   # initialize the pop DNA


def F(x):
    error = 0
    fitness =0     
    y = x[0] * 1
    return y

def getFintness(pop):
    pop = pop[np.lexsort(pop.T)]
    return pop[0,:-1]
      

def select(pop, new):   
    for i,_ in enumerate(new) :
        i_finess = F(_[:-1])
        global MFE_COUNT
        MFE_COUNT = MFE_COUNT + 1
        new[i,-1] = i_finess
    pop = np.row_stack((pop,new))
    pop = pop[np.lexsort(pop.T)]
#     pop_row = pop.shape[0]
#     pop_col = pop.shape[1]
    #pop = pop[pop_row - 1 - POP_SIZE :pop_row - 1, :] # 找最大 排序200 個 由小排到大
    pop = pop[:POP_SIZE,:]
    return pop   
def crossover(pop,copy):
    temp =[0] * (DNA_SIZE + 1)
    for i in range (DNA_SIZE):
        if np.random.rand() < CROSS_RATE:
            r = np.random.rand() 
            i_ = 1 - r 
            x =  np.random.randint(POP_SIZE)
            
            temp[i] = r * pop[i] + i_ * copy[x,i]
    return temp
        
def mutate(child):
    for i in range (DNA_SIZE ):     
        if np.random.rand() < MUTATION_RATE:
            a = np.random.uniform(X_BOUND[0] ,DNA_MAX)
            child[i] = a
    return child

                     
                
def GA():
    temp = np.random.uniform(DNA_MAX, size=(POP_SIZE, DNA_SIZE + 1))
    global pop
    while( MFE_COUNT < MFE):   
        pop = select(pop, temp )
        temp = np.zeros( (1 , DNA_SIZE  + 1 ) )
        new  = pop.copy()   
        for parent in pop:
            child = crossover(parent, new)
            child = mutate(child)
            temp = np.row_stack((temp,child))
        
        temp = np.delete(temp, [0], axis=0)
        print(MFE_COUNT,"最好的基因",getFintness(pop))
        print(MFE_COUNT,"最好的分數",F(getFintness(pop)))


In [85]:
GA()

[[ 2.2094223   0.16533735  3.81106189  3.66110156]
 [ 0.48681469  4.67460353 -0.33288575  0.126871  ]
 [-2.96518578 -1.65132084  4.36332018 -2.41853582]
 [ 3.77713716 -0.21605273 -2.9531137  -2.04115022]
 [ 3.24440628  4.58286357  3.36055202  0.75441069]
 [-2.90422999 -0.27527528  3.98305891  0.45215404]
 [ 4.53128069  3.47894096  0.1509517   0.78504681]
 [-1.70288588  2.62974628  1.81216914  0.08196096]
 [ 2.56976094  2.46486721  3.61853754  1.47508439]
 [ 4.34682607  4.22774106 -1.66706689 -2.60488263]
 [ 1.45641344  2.25701524  2.53710149  1.45641344]
 [ 4.66783274  4.5969723   2.80472994  4.66783274]
 [ 3.34756761  3.28636861  2.58355723  3.34756761]
 [ 1.36232685  1.76620687  3.20160188  1.36232685]
 [ 2.66431424  3.73659851  3.50120492  2.66431424]
 [ 2.78491398  1.19697761  1.63290251  2.78491398]
 [ 2.35248361  3.70054262  1.1239108   2.35248361]
 [ 1.78439171  1.69994204  2.99741137  1.78439171]
 [ 1.11235818  4.46350041  4.65832518  1.11235818]
 [ 1.23854734  2.05706025  4.66